### ISSUE TITLE
进入shuke之后info中找不到stats

### ISSUE THREAD

**Issue by chaunch** [yuyang0/shuke#4]
stats中有log等信息么

**Comment by yuyang0** [comment]
什么log信息呢? 提问题还是请详细说明下

**Comment by chaunch** [comment]
DNS服务器是否在运行、请求数量等信息可以保存成文件或者提供指令获得么

**Comment by yuyang0** [comment]
info命令的返回结果不就有请求总数吗? 这是参照redis的那个命令写的,其实返回json更好一些, 至于说在不在运行你检测pid文件

**Comment by chaunch** [comment]
感谢！有具体指令可以返回json吗
